# Generated by Django 5.1.1 on 2024-10-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Уникальный ID администратора в Telegram', unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(blank=True, help_text='Имя администратора', max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия администратора', max_length=255, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, help_text='Имя пользователя администратора в Telegram', max_length=255, null=True, verbose_name='Имя пользователя')),
                ('language_code', models.CharField(blank=True, help_text='Код языка по умолчанию, установленный у администратора', max_length=10, null=True, verbose_name='Код языка')),
                ('is_bot', models.BooleanField(blank=True, default=False, help_text='Указывает, является ли этот пользователь ботом', null=True, verbose_name='Является ботом')),
                ('is_premium', models.BooleanField(blank=True, default=False, help_text='Отмечает, есть ли у администратора премиум-статус', null=True, verbose_name='Премиум пользователь')),
                ('cteated_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Telegram администратор',
                'verbose_name_plural': 'Telegram администраторы',
                'ordering': ['-cteated_at'],
            },
        ),
    ]
